### ISSUE TITLE
Receiving Plain Text Instead of the Original Text in the NYT Puzzle

### ISSUE THREAD

**Issue by craggi** [thisisparker/xword-dl#113]
In the NYT multilingual puzzle, there is a problem where the plain text is being retrieved instead of the original formatted text. To resolve this issue, a piece of code has been implemented by me to ensure that the original `text` is obtained instead of the plain text and first Observed on 5th July. 

PS: I am not creating Puz File, so I am not sure whether the below code works with the Puz file.

`puzzle.clues = []
for c in clue_list:
    if 'formatted' in c['text'][0]:
        result = c['text'][0].get('formatted')
    else:
        result = unidecode(c['text'][0]['plain'])
    puzzle.clues.append(result)
`

**Comment by thisisparker** [comment]
Thank you for this issue. I'm going to close it because I think the current behavior is expected for `xword-dl`'s purposes, but I understand that may be a surprise if you're not ultimately producing a puz file.

`unidecode` is a lossy and automated conversion function, so I prefer not to use it to introduce edits into the resulting files except where necessary. I only use it at all here because of the limitations of puz files with character encoding. The `plain` field from NYT is also a lossy conversion but it is manually done so it takes priority. In a real sense, the `plain` text provided in the underlying JSON _is_ "original" in a way that a `unidecode`d version is not.

If you're not making puz files though, you don't have those limitations! I've structured this package to make it easy to maintain forks of individual downloaders if you want to do it that way.
