### ISSUE TITLE
Handling of italics in clues

### ISSUE THREAD

**Issue by fakelvis** [thisisparker/xword-dl#89]
If (part of) a clue is in italics, it is currently parsed and shown with underscores, rather than being in italics.

As an example, 67A of Friday 6 January's New Yorker puzzle displayed:

> **Type of bean in \_ful\_ \_medames\_**

Edit: related to #9?

**Comment by aanker** [comment]
I think the issue is no support for italics in PUZ files.

**Comment by thisisparker** [comment]
@aanker is correct, the underlying issue here is that puz files do not support any kind of markup natively, and so can't guarantee any kind of formatting. When scraping puzzles from a source that _does_ support formatting, the options I see are:
- include the html tags from the original (so that clue would read `Type of bean in <i>ful</i> <i>medames</i>`),
- strip it out entirely (so that clue would read `Type of bean in ful medames`), or
- convert to something human-readable like markdown, where `<i>` tags are represented with underscores. (Markdown is pretty universal and e.g., the way that you'd indicate `_italics_` here in Github comments.)

I've chosen the last option, which is admittedly opinionated but feels like the right choice to me. In this case it's kind of a shame that the New Yorker put the tags around each word instead of around the phrase, but I still like the trade-off.

One note: nothing prevents a client from parsing markdown or HTML when you open the puz file! If I knew that there clients out there that were parsing markdown or HTML, I could imagine making some affordances for that. But I'm not aware of that happening client-side.

**Comment by aanker** [comment]
I haven't run into any either.  I looked into this a few months ago because I was going to suggest a fix and then realized the issue wasn't this software but client side. Although I couldn't find it documented anywhere, it looked like JPZ might support formatting but since there's not really enough support on the client side for that format, it just seemed like something not worth chasing down.

**Comment by blandford** [comment]
I'd love for the html tags to stay in the puz file, if possible. GNOME Crosswords parses html in clues (and metadata) as per the ipuz spec. We also keep the HTML tags from JPZ files. When converting from .puz files to .ipuz, we try to keep certain tags (such as <i> and <b>), though it's a heuristic at best. I didn't realize that xword-dl was changing them to markdown ­— if you keep this functionality I'll add another heuristic to the convertor.

**Comment by thisisparker** [comment]
This is a compelling request! Would it be sufficient for you to have some kind of `--preserve-html` flag to pass at runtime, @blandford? I try not to make substantive or lossy conversions, but I do still feel like by default most users will not expect html tags in their puz files, so I'd prefer not to have that go as the default.

**Comment by blandford** [comment]
That flag is exactly what I'm looking for! I'm happy to pass that in as a
non-standard feature.
